<a href="https://colab.research.google.com/github/GaiaFL/Projet-Cassiopee/blob/main/Modelo1_Gabriel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tabula-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 102.4 MB/s eta 0:00:00


#Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import ast
from sklearn.metrics import mean_squared_error
from math import sqrt
import math
import gdown
from tabula.io import read_pdf
import glob

# Load Dataset

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A0.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A1.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A2.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A3.csv'

! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20B0.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20B1.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20B2.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20B3.csv'

! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20E0.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20E1.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20E2.csv'
! wget 'https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20E3%20(2).csv'


--2023-06-11 00:42:21--  https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A0.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1718 (1.7K) [text/plain]
Saving to: ‘Dataset - A0.csv’

Dataset - A0.csv    100%[===================>]   1.68K  --.-KB/s    in 0s      

2023-06-11 00:42:21 (28.0 MB/s) - ‘Dataset - A0.csv’ saved [1718/1718]

--2023-06-11 00:42:21--  https://raw.githubusercontent.com/GaiaFL/Projet-Cassiopee/main/Database/Dataset%20-%20A1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Len

#DataSet Gabriel 

In [5]:
df_A0 = pd.read_csv('Dataset - A0.csv')
df_A1 = pd.read_csv('Dataset - A1.csv')
df_A2 = pd.read_csv('Dataset - A2.csv')
df_A3 = pd.read_csv('Dataset - A3.csv')

df_B0 = pd.read_csv('Dataset - B0.csv')
df_B1 = pd.read_csv('Dataset - B1.csv')
df_B2 = pd.read_csv('Dataset - B2.csv')
df_B3 = pd.read_csv('Dataset - B3.csv')


df_E0 = pd.read_csv('Dataset - E0.csv')
df_E1 = pd.read_csv('Dataset - E1.csv')
df_E2 = pd.read_csv('Dataset - E2.csv')
df_E3 = pd.read_csv('Dataset - E3 (2).csv')


Inserting the places into the data sets

In [6]:
df_A0['place'] = 'A0'
df_A1['place'] = 'A1'
df_A2['place'] = 'A2'
df_A3['place'] = 'A3'

df_B0['place'] = 'B0'
df_B1['place'] = 'B1'
df_B2['place'] = 'B2'
df_B3['place'] = 'B3'

df_E0['place'] = 'E0'
df_E1['place'] = 'E1'
df_E2['place'] = 'E2'
df_E3['place'] = 'E3'



In [7]:
df_A0['coord'] = '[48.6246723,  2.4425536]'
df_A1['coord'] = '[48.6246723,  2.4425536]'
df_A2['coord'] = '[48.6246723,  2.4425536]'
df_A3['coord'] = '[48.6246723,  2.4425536]'

df_B0['coord'] = '[48.6245008, 2.442969]'
df_B1['coord'] = '[48.6245008, 2.442969]'
df_B2['coord'] = '[48.6245008, 2.442969]'
df_B3['coord'] = '[48.6245008, 2.442969]'

df_E0['coord'] = '[48.6246723,  2.4425536]'
df_E1['coord'] = '[48.6246723,  2.4425536]'
df_E2['coord'] = '[48.6246723,  2.4425536]'
df_E3['coord'] = '[48.6246723,  2.4425536]'

In [8]:
data = pd.concat([df_A0, df_A1, df_A2, df_A3, df_B0, df_B1, df_B2, df_B3, df_E0, df_E1, df_E2, df_E3])
#data['max_rssi'] = data['max_rssi'].astype(int)
#data['rssi'] = data['rssi'].astype(int)
data['delta'] = data['Max RSSI'] - data['RSSI']
data

Status       SSID  RSSI        MAC Address  Max RSSI place  \
0   Available    eduroam   -82  04-DA-D2-90-09-61       -82    A0   
1   Available  SDN_SCADA   -85  B8-27-EB-20-A7-65       -85    A0   
2   Available    eduroam   -70  CC-16-7E-13-20-81       -67    A0   
3   Available    eduroam   -78  04-DA-D2-AA-5B-81       -74    A0   
4   Available    eduroam   -79  04-DA-D2-AA-5B-8E       -77    A0   
..        ...        ...   ...                ...       ...   ...   
27  Available    eduroam   -85  50-06-04-5B-1C-61       -84    E3   
28  Available    eduroam   -68  20-BB-C0-4B-9F-81       -66    E3   
29  Available    eduroam   -65  20-BB-C0-4B-9F-8E       -63    E3   
30  Available    eduroam   -48  20-BB-C0-4B-97-B1       -41    E3   
31  Available    eduroam   -41  20-BB-C0-4B-97-BE       -41    E3   

                       coord  delta  
0   [48.6246723,  2.4425536]      0  
1   [48.6246723,  2.4425536]      0  
2   [48.6246723,  2.4425536]      3  
3   [48.6246723,  2.4425536]      4  
4   [48.6246723,  2.4425536]      2  
..                       ...    ...  
27  [48.6246723,  2.4425536]      1  
28  [48.6246723,  2.4425536]      2  
29  [48.6246723,  2.4425536]      2  
30  [48.6246723,  2.4425536]      7  
31  [48.6246723,  2.4425536]      0  

[421 rows x 8 columns]

In [9]:
data.csv = data.to_csv(path_or_buf="/content/drive/MyDrive/Prediction/data.csv")

In [10]:
rssi_values = []
place = ['A0', 'A1', 'A2', 'A3','E0', 'E1', 'E2', 'E3', 'B0', 'B1', 'B2', 'B3']

for x in place:
  prev = data.loc[data['place'] == x]
  #connect = prev[prev['status'] == 'Connected']
  prev = prev.sort_values(by='delta', ascending=False)
  #rssi_values.append(pd.concat([connect['rssi'].astype(int), prev['rssi'].astype(int)]).values)
  rssi_values.append(prev['RSSI'].astype(int).values)
x = np.array(rssi_values)
#y = places

<ipython-input-10-82bed6eeb135>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(rssi_values)


# Split Dataset

In [11]:
data.columns

Index(['Status', 'SSID', 'RSSI', 'MAC Address', 'Max RSSI', 'place', 'coord',
       'delta'],
      dtype='object')

In [28]:
x = data[['RSSI', 'Max RSSI', 'delta']].values
y = data['place']

X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state = 0)


#KNN Algorithm

In [29]:
class KnnLocalizer:

    """ KNN Regression Class for indoor localization using a 3-dimensional label space
        e.g.  Longitude, Latitude, and Floor

    Attributes:
        features - training data features - Average RSSI
        labels -  training data labels - Coordinates
        k (int) number of nearest neighbors

    """

    def __init__(self, features, labels, k=3):

        self.features = np.array(features)
        self.labels = np.array(labels)
        self.k = k

    @staticmethod
    def euclidean_distance(array1, array2): #Calculate the difference between each RSSI

        """ Euclidean distance function without squareroot taken for efficiency
		Args:
			Two arrays of equal length

		Returns:
			Distance squared between RSSI1 and RSSI2
		"""
        print(array1) #wifi fingerprint
        print(array2) #dataset
        distance = np.sum((array1-array2)**2)
        distance = math.sqrt(distance)  
        return distance
    
    @staticmethod
    def timsort(array, element):

        """ Sort method based on Python's sort() function that sorts tuples in descending order

        Args:
            array (array or list of tuples) array of tuples containing distance and label
            element (Int) the index of the element within tuple that is used to sort tuples

        Returns:
            Array of tuples sorted in descending order at index given by element
        """

        array.sort(key=lambda tup: tup[element])
        return array


    def knn_regression(self, instance):

        """ KNN regression function modified to return regression predictions
         of 3-dimensional labelspace: (RSSI, logitude, latitude).

        Args:
            Test_features (array) test RSSI for which to predict location

        Returns:
            An array containing the top 3 predicted coordinates
        """
        size_input = len(instance)
        temp_results = []
        for i in range(len(self.features)):
            
            RSSI = self.euclidean_distance(instance, self.features[i][:size_input])
            temp_results.append((self.labels[i], RSSI)) #each localisation with the difference of RSSI   
        sorted_distances = self.timsort(temp_results, 1)
        return sorted_distances[:3] #return the 3 localisation with minimum RSSI 

    def fit_predict(self, test_data):

        """ KNN Localizer prediction function

        Args:
        	test_data (array) test RSSI

        Returns:
        	List of arrays containing coordinate predictions
        """

        predictions = []
        for sample in test_data:
            predictions.append(self.knn_regression(sample))
        return predictions

In [30]:
MAX_CHARS = 128
def get_mean_point(points, debug=False):
  # Inicializar variável de retorno
  mean_point = [0,0]

  try:
    if len(points) > 0:
      # Calcular o ponto médio do conjunto
      for point in points:
        mean_point[0] += point[0]
        mean_point[1] += point[1]
      mean_point = [mean_point[0]/len(points), mean_point[1]/len(points)]

  except:
    print('[get_mean_point] ERROR: points [' + str(len(points)) + '] = ' + str(points)[:MAX_CHARS])
  finally:
    if debug:
      print('[get_mean_point] debug: mean_point = ' + str(mean_point))

  return mean_point

In [33]:
localizer = KnnLocalizer(x, y, 1)
new_predictions = localizer.fit_predict(np.array([[-41, -40, 1]]))
print(new_predictions[0][0][0])
map = [i[0][1] for i in new_predictions[0]]
print([i[0][0] for i in new_predictions[0]])
pl_x = [i[0][1][0] for i in new_predictions[0]]
#print(pl_x)
#pl_y = [i[0][1][1] for i in new_predictions[0]]
#print(pl_y)
mean = get_mean_point(map)
#print(mean)

[-41 -40   1]
[-82 -82   0]
[-41 -40   1]
[-85 -85   0]
[-41 -40   1]
[-70 -67   3]
[-41 -40   1]
[-78 -74   4]
[-41 -40   1]
[-79 -77   2]
[-41 -40   1]
[-63 -63   0]
[-41 -40   1]
[-83 -79   4]
[-41 -40   1]
[-86 -86   0]
[-41 -40   1]
[-83 -80   3]
[-41 -40   1]
[-85 -85   0]
[-41 -40   1]
[-54 -49   5]
[-41 -40   1]
[-53 -51   2]
[-41 -40   1]
[-67 -61   6]
[-41 -40   1]
[-73 -70   3]
[-41 -40   1]
[-91 -91   0]
[-41 -40   1]
[-70 -64   6]
[-41 -40   1]
[-73 -69   4]
[-41 -40   1]
[-71 -67   4]
[-41 -40   1]
[-89 -89   0]
[-41 -40   1]
[-72 -60  12]
[-41 -40   1]
[-80 -80   0]
[-41 -40   1]
[-70 -64   6]
[-41 -40   1]
[-72 -72   0]
[-41 -40   1]
[-81 -81   0]
[-41 -40   1]
[-56 -56   0]
[-41 -40   1]
[-54 -54   0]
[-41 -40   1]
[-78 -75   3]
[-41 -40   1]
[-77 -77   0]
[-41 -40   1]
[-81 -78   3]
[-41 -40   1]
[-74 -71   3]
[-41 -40   1]
[-83 -73  10]
[-41 -40   1]
[-72 -69   3]
[-41 -40   1]
[-89 -85   4]
[-41 -40   1]
[-44 -36   8]
[-41 -40   1]
[-41 -39   2]
[-41 -40   1]
[-85 -

In [ ]:
plt.style.use('seaborn')
plt.figure(figsize = (10,10))
plt.scatter(pl_x, pl_y, marker= '*',s=100,edgecolors='black')
plt.scatter(mean[0], mean[1], marker= '.',s=100,edgecolors='black')

In [ ]:
distances = []
for x in map:
  distances.append(localizer.euclidean_distance(np.array(mean), np.array(x)))

min_pos = distances.index(min(distances))
pos = new_predictions[0][min_pos]
print(pos[0][0])



# Comparison of Results

In [ ]:
#Needs to compare the predictions with the test dataset
new_predictions = np.asarray(new_predictions)
print('Predictions made:\n', new_predictions)
print('Testing values\n', y_test)
n = len(y_test)

new_predictions_2 = np.split(new_predictions, n)
#print(new_predictions_2)

y_test_equalized = [arr.flatten() for arr in y_test]
print('Testing values equals\n',y_test_equalized)

new_predictions_equalized = [arr.flatten() for arr in new_predictions]
print('Predictions made equals:\n',new_predictions_equalized)

mse2 = mean_squared_error(y_test_equalized, new_predictions_2)
print('MSE:\n', mse2)
 #Gives error, improves it pls

In [ ]:

#Needs to compare the predictions with the test dataset
new_predictions = np.asarray(new_predictions)

y_test_div = np.concatenate(y_test)
new_predictions_div = np.concatenate(new_predictions)

print(new_predictions_div)
print(y_test_div)

mse = mean_squared_error(y_test_div, new_predictions_div)
print(mse) 

 #I tried to concatenate the two arrays but I don't think the result is sufficient

In [ ]:
2.711674309998789e-07
